---
title: "TidyTuesday week 5 (2023)"
author: "Christian Gebahrd"
format: html
---

## read data and load libraries
```{r}
library(tidyverse)
library(lubridate)
library(systemfonts)
library("ggtext")
library("ggrepel")

```

```{r}
tuesdata <- tidytuesdayR::tt_load(2023, week = 5)

cats_uk <- tuesdata$cats_uk |> 
  filter(visible == TRUE) |> 
  # assuming ground speed is given as m/h:
  mutate(speed_mps = ground_speed / 3600)

cats_uk_reference <- tuesdata$cats_uk_reference
```

## data preparation

```{r}
median_speeds_mps <- cats_uk |> 
  
  # remove records with speed = 0, as I'm only interested in moving speed, not counting when cats are sitting
  filter(
    ground_speed != 0
  ) |> 
  group_by(tag_id) |> 
  summarise(
    speed_mps_median = median(speed_mps, na.rm = TRUE)
  ) |> 
  ungroup()
  
cats_with_speed <- cats_uk_reference |> 
  left_join(median_speeds_mps, by = "tag_id") |> 
  mutate(
    months_deployed = as.period(interval(start = deploy_on_date, end = deploy_off_date)) / months(1),
    prey_absolute = prey_p_month * months_deployed
  )
```

## Plot

```{r}
text_colour <- "grey90"
title <-  "Pet cats moving speed by age"
subtitle <- "
Older pet cats in the UK had a similar median moving speed as the younger ones.<br>
However, they don't seem to catch as much prey, as most of the <span style='color: #fcde9c; font-weight: bold;'>very successful hunters </span> were<br>
six years or younger. Larger points indicate higher prey-count per month.
"

cats_with_speed_max <- cats_with_speed |> 
  filter(
    prey_p_month > 17 | animal_id == "Tommy"
  )

ggplot(cats_with_speed) +
  aes(
    x = age_years,
    y = speed_mps_median,
  ) +
  geom_point(
    aes(
      size = prey_p_month,
      fill = prey_p_month,
      color = after_scale(fill)
      ), 
    shape = 21, alpha = .3, stroke = .7,
    position = position_jitter(width = 0.1, seed = 42)
  ) +
  geom_text_repel(
    aes(
      label = animal_id
    ),
    data = cats_with_speed_max,
    color = "grey90",
    family = "Titan One",
    face = "bold",
    size = 6,
    nudge_y = 0.15,
    hjust = 0.1,
    label.padding = 0.5
  ) +
  annotate(
    geom = "curve", 
    xend = 3, x = 4,
    yend = 1, y = 0.9,
    curvature = -0.3,
    arrow = arrow(length = unit(3, "mm")),
    color = "grey90"
  ) +
  annotate(
    geom = "text",
    x = 4.1, y = 0.93,
    label = "Magic",
    family = "Titan One",
    size = 4,
    colour = "grey90",
    hjust = 0
  ) + 
  annotate(
    geom = "text",
    x = 4.1, y = 0.88,
    label = "She's the most active cat by far. Her median\nmoving speed is roughly twice as high,\nas what the other cats recorded.",
    family = "Figtree",
    size = 3.5,
    colour = "grey70",
    hjust = 0
  ) + 
  scale_size_area(
    max_size = 15
  ) +
  coord_cartesian(clip = 'off', xlim = c(0,13)) +
  rcartocolor::scale_fill_carto_c(palette = "SunsetDark", direction = -1) +
  labs(
    title = title,
    subtitle = subtitle,
    x = "age [years]",
    y = "median moving speed [m/s]\n",
    caption = "DataViz by Christian Gebhard <span style='font-family: Font Awesome 6 Brands; color: grey90'>&#xf4f6;</span> @basepair@<span style='color: grey5;font-size:1px'>'</span>vis.social<br>for #TidyTuesday week 5 (2023)<br>Data by Kays et. al. [doi:10.1111/acv.12563] via Movebank Data Repository"
    ) +
  theme_void()+
  theme(
    legend.position = "none",
    plot.title.position = "plot",
    plot.title = element_text(family = "Titan One", size = 48),
    plot.subtitle = element_markdown(size = 24),
    plot.caption.position = "plot",
    plot.caption = element_markdown(family = "Figtree", size = 10, color = "grey60", lineheight = 0.9),
    text = element_text(family = "Figtree", size = 12, lineheight = 0.8, colour = text_colour),
    plot.margin = margin(b = 20, t = 50, r = 50, l = 50),
    plot.background = element_rect(fill = "grey5"),
    axis.text = element_text(face = "bold", colour = "grey60"),
    axis.title.y = element_text(size = 12, angle = 90, vjust = 0.5, colour = "grey60"),
    axis.title.x = element_text(size = 12, colour = "grey60")
  )

ggsave(filename = here::here("2023-05", "cats.png"), width = 16, height = 10)

```