---
title: "TidyTuesday Week 2021-24: Great Lakes Commercial Fishing"
author: Christian A. Gebhard
date: 2021-06-14
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      collapse = FALSE,
                      comment = "#>",
                      fig.retina = 2, 
                      fig.width = 6,  
                      fig.align = "center",
                      dpi = 72, 
                      out.width = "100%",
                      dev = "png",
                      dev.args = list(png = list(type = "cairo-png")),
                      optipng = "-o1 -quiet")

```

```{r libraries and setup, include=FALSE}
library(tidyverse)

library("ggplot2")
library("showtext")
font_add_google("Bitter")
font_add_google("Open Sans")
showtext_auto()

library(emojifont)
library(ggbeeswarm)


my_theme <- function(base_size = 10,
                        base_family = "Open Sans",
                        h_just = 0) {
  theme_minimal(
    base_size = base_size,
    base_family = base_family
  ) %+replace%
    theme(
      plot.title = element_text(
        family = "Bitter",
        face = "bold",
        size = rel(1.8),
        hjust = h_just,
        vjust = 10
      ),
      plot.title.position = "plot",
      plot.subtitle = element_text(
        face = "italic",
        size = rel(1.4),
        hjust = h_just,
        vjust = 9
      ),
      plot.caption = element_text(
        size = rel(1.2),
        face = "italic",
        hjust = 1
      ),
      plot.caption.position =  "plot",
      plot.margin = margin(1.5, 0.4, 0.4, 0.4, unit = "cm"),
      axis.title = element_text(
        face = "bold",
        size = rel(1.4)
      ),
      axis.title.x = element_text(margin = margin(t = 15, r = 0, b = 0, l = 0)),
      axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0), angle = 90),
      axis.text = element_text(
        size = rel(1.4)
      ),
      legend.position = "bottom",
      legend.title = element_text(
        face = "bold",
        size = rel(1.4)
      ),
      complete = TRUE
    )
}

```


```{r load data, echo=FALSE, include=FALSE}
tuesdata <- tidytuesdayR::tt_load('2021-06-08')

fishing <- tuesdata$fishing

```

```{r read and inspect}
head(fishing)

glimpse(fishing)
```


```{r clean and prepare}
fishing_clean <- fishing |>
  mutate(
    species = case_when(
      str_detect(species, "[Cc]atfish|[Bb]ullhead") ~ "Channel Catfish and Bullheads",
      str_detect(species, "[Cc]isco|[Cc]hub") ~ "Cisco and Chubs",
      str_detect(species, "[Ww]alleye|(Blue Pike)") ~ "Walleye and Blue Pike",
      str_detect(species, "[Rr]ock [Bb]ass|[Cc]rappie") ~ "Rock Bass and Crappie",
      str_detect(species, "[Pp]acific [Ss]almon") ~ "Pacific Salmon",
      TRUE ~ species
    )
  ) |>
  filter(
    region %in% c("U.S. Total", "Total Canada (ONT)"),
    !is.na(values)
  ) |>
  group_by(species, year) |>
  mutate(yearly_total_US_CA = sum(values)) |> 
  distinct(year, species, yearly_total_US_CA)

 
fishing_filtered <- fishing_clean |> 
  group_by(species) |> 
  summarise(t = sum(yearly_total_US_CA)) |>
  filter(t > 500000)

fishing_final <- fishing_clean |> 
  right_join(fishing_filtered, by = "species")


```


```{r, fig.width=6, fig.height=12}
# list.emojifonts()
load.emojifont("OpenSansEmoji.ttf")


fishing_final |> 
  mutate(ktonnes = round(yearly_total_US_CA * 0.4535924 * 0.001)) |> 
  uncount(ktonnes) |> 
  ggplot(aes(x=species, y=year, color = species)) +
    geom_text(label = emoji("fish"), family="OpenSansEmoji", size=4, alpha = 0.3, position = position_quasirandom(bandwidth = 0.75, varwidth = F)) +
    # geom_quasirandom() +
    labs(
      title = "Commercial Fish Production in the Great Lakes 1867-2015",
      subtitle = "Combined (US + CA) commercial production of the 6 most prominent species\nof fish in Lakes Erie, Michigan, Superior",
      y = "Year",
      caption = "\nSource: Great Lakes Fishery Commission | by @c_gebhard for week 2021-24 of #TidyTuesday"
    ) +
    scale_y_continuous(
      breaks = c(1900, 1950, 2000), 
      minor_breaks = c(1879, 1880, 1890, 1910, 1920, 1930, 1940, 1960, 1970, 1980, 1990, 2010)
      ) +
    scale_color_manual(values =  c("#F39F5C", "#EC836D", "#2D7F89", "#E86B72", "#29BCCE", "#56BB83")) +
    coord_flip() +
    my_theme() +
    theme(
      legend.position = "none",
      axis.title.y = element_blank())
  

ggsave(last_plot(), filename = "2021-24_TT_fishing.pdf",device = "pdf", 
                width = 10, height = 20, dpi = 500)
```




